export const enum GameAbilities {



    UNIT_BASH_TIER_1 = "A00K",
    UNIT_SEARING_ARROWS_TIER_1 = "A00L",
    UNIT_UNDYING_BRAVERY_TIER_1 = "A00I",
    UNIT_ABOLISH_MAGIC_TIER_1 = "A00H",
    UNIT_CANNIBALIZE_TIER_1 = "A00G",
    UNIT_ENSNARE_TIER_1 = "A003",
    UNIT_ENVENOMED_WEAPONS_TIER_1 = "A009",
    UNIT_FRENZY_TIER_1 = "A001",
    UNIT_FROST_ARMOR_TIER_1 = "A008",
    UNIT_HEAL_TIER_1 = "A005",
    UNIT_REJUVENATION_TIER_1 = "A00M",
    UNIT_SLOW_TIER_1 = "A006",
    UNIT_UNHOLY_FRENZY_TIER_1 = "A00N",


    HERO_HEALING_WAVE = "A00J",
    HERO_SHOCKWAVE = "A007",
    HERO_THUNDER_CLAP = "A00A",
    HERO_WAR_VETERAN_A4 = "A004",


    TEST_BERSERK = "A002",


    ITEM_HEALING_SALVE_TIER_1 = "A00B",
    ITEM_AREA_HEALING_TIER_1 = "A00D",
    ITEM_LESSER_CLARITY_POTION_TIER_1 = "A00C",
    ITEM_SCROLL_OF_HASTE_TIER_1 = "A00E",
    ITEM_SCROLL_OF_REGENERATION_TIER_1 = "A00F",

    ITEM_ARMOR_SHARD_ARMOR_BONUS= "A00P",
    ITEM_WEAPON_PART_DAMAGE_BONUS= "A000",



}