export const enum PlayerUnits {
    HERO_GRAND_GENERAL = "H000",


    MELEE_SOLDIER = "h001",

    RANGER_ARCHER = "h002",
    RANGER_FOREST_TROLL = "h003",

    CASTER_PRIEST = "h004",
    CASTER_SORCERESS = "h005",

    CAVALRY_KNIGHT = "h006",

    ARTILLERY_DEMOLISHER = "o000",


    HALL_FORCE_1 = "e000",
    HALL_FORCE_2 = "e000",
    HALL_FORCE_BANDITS = "e000",
}