gg_trg_Untitled_Trigger_001 = nil
gg_rct_force1spawner1 = nil
gg_rct_force1spawner2 = nil
gg_rct_force1spawner3 = nil
gg_rct_force2spawner1 = nil
gg_rct_force2spawner2 = nil
gg_rct_force2spawner3 = nil
gg_rct_force1gathering = nil
gg_rct_force2gathering = nil
function InitGlobals()
end

function CreateRegions()
    local we
    gg_rct_force1spawner1 = Rect(-28224.0, 27712.0, -28096.0, 27840.0)
    gg_rct_force1spawner2 = Rect(-24896.0, 28704.0, -24768.0, 28832.0)
    gg_rct_force1spawner3 = Rect(-29152.0, 24832.0, -29024.0, 24960.0)
    gg_rct_force2spawner1 = Rect(28096.0, -28672.0, 28224.0, -28544.0)
    gg_rct_force2spawner2 = Rect(28800.0, -25696.0, 28928.0, -25568.0)
    gg_rct_force2spawner3 = Rect(24544.0, -29600.0, 24672.0, -29472.0)
    gg_rct_force1gathering = Rect(-25952.0, 25440.0, -24128.0, 26144.0)
    gg_rct_force2gathering = Rect(24416.0, -26944.0, 25920.0, -26496.0)
end

function Trig_Untitled_Trigger_001_Actions()
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerRegisterUnitEvent(gg_trg_Untitled_Trigger_001, nil, EVENT_UNIT_ISSUED_POINT_ORDER)
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(10), false)
    SetPlayerController(Player(10), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(11), 11)
    ForcePlayerStartLocation(Player(11), 11)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(11), false)
    SetPlayerController(Player(11), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(12), 12)
    ForcePlayerStartLocation(Player(12), 12)
    SetPlayerColor(Player(12), ConvertPlayerColor(12))
    SetPlayerRacePreference(Player(12), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(12), false)
    SetPlayerController(Player(12), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(13), 13)
    ForcePlayerStartLocation(Player(13), 13)
    SetPlayerColor(Player(13), ConvertPlayerColor(13))
    SetPlayerRacePreference(Player(13), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(13), false)
    SetPlayerController(Player(13), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(14), 14)
    ForcePlayerStartLocation(Player(14), 14)
    SetPlayerColor(Player(14), ConvertPlayerColor(14))
    SetPlayerRacePreference(Player(14), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(14), false)
    SetPlayerController(Player(14), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(15), 15)
    ForcePlayerStartLocation(Player(15), 15)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(15), false)
    SetPlayerController(Player(15), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(16), 16)
    ForcePlayerStartLocation(Player(16), 16)
    SetPlayerColor(Player(16), ConvertPlayerColor(16))
    SetPlayerRacePreference(Player(16), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(16), false)
    SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(17), 17)
    ForcePlayerStartLocation(Player(17), 17)
    SetPlayerColor(Player(17), ConvertPlayerColor(17))
    SetPlayerRacePreference(Player(17), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(17), false)
    SetPlayerController(Player(17), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(18), 18)
    ForcePlayerStartLocation(Player(18), 18)
    SetPlayerColor(Player(18), ConvertPlayerColor(18))
    SetPlayerRacePreference(Player(18), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(18), false)
    SetPlayerController(Player(18), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(19), 19)
    ForcePlayerStartLocation(Player(19), 19)
    SetPlayerColor(Player(19), ConvertPlayerColor(19))
    SetPlayerRacePreference(Player(19), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(19), false)
    SetPlayerController(Player(19), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(20), 20)
    ForcePlayerStartLocation(Player(20), 20)
    SetPlayerColor(Player(20), ConvertPlayerColor(20))
    SetPlayerRacePreference(Player(20), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(20), false)
    SetPlayerController(Player(20), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(21), 21)
    ForcePlayerStartLocation(Player(21), 21)
    SetPlayerColor(Player(21), ConvertPlayerColor(21))
    SetPlayerRacePreference(Player(21), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(21), false)
    SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(22), 22)
    ForcePlayerStartLocation(Player(22), 22)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(23), 23)
    ForcePlayerStartLocation(Player(23), 23)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(3), 0)
    SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(4), 0)
    SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(5), 0)
    SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(6), 0)
    SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(7), 0)
    SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(18), 0)
    SetPlayerState(Player(18), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(19), 0)
    SetPlayerState(Player(19), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(20), 0)
    SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(19), true)
    SetPlayerAllianceStateAllyBJ(Player(18), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(19), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(18), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(19), true)
    SetPlayerAllianceStateVisionBJ(Player(18), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(19), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(18), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(19), true)
    SetPlayerTeam(Player(8), 1)
    SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(9), 1)
    SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(10), 1)
    SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(11), 1)
    SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(12), 1)
    SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(13), 1)
    SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(14), 1)
    SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(15), 1)
    SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(21), 1)
    SetPlayerState(Player(21), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(22), 1)
    SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(23), 1)
    SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(12), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(13), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(14), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(21), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(12), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(13), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(14), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(21), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(12), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(13), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(14), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(21), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(12), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(13), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(14), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(21), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(22), true)
    SetPlayerTeam(Player(16), 2)
    SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(17), 2)
    SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
    SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
    SetPlayerAllianceStateVisionBJ(Player(16), Player(17), true)
    SetPlayerAllianceStateVisionBJ(Player(17), Player(16), true)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 3)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 1, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 2, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(1, 5)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(1, 3, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 4, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(2, 5)
    SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 3, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 4, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(3, 3)
    SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(3, 2, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 3)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 2, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 5)
    SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(5, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 4, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 5)
    SetStartLocPrio(6, 0, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 2, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(6, 3, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 4, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 3)
    SetStartLocPrio(7, 0, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(7, 1, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 3)
    SetStartLocPrio(8, 0, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 2, 13, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(9, 5)
    SetStartLocPrio(9, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 2, 12, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 3, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 4, 14, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(10, 5)
    SetStartLocPrio(10, 0, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 1, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 2, 13, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 3, 14, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 4, 15, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(11, 3)
    SetStartLocPrio(11, 0, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 1, 14, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 2, 15, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(12, 3)
    SetStartLocPrio(12, 0, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 1, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(12, 2, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(13, 5)
    SetStartLocPrio(13, 0, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 1, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(13, 2, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 3, 12, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(13, 4, 14, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(14, 5)
    SetStartLocPrio(14, 0, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(14, 1, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 2, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(14, 3, 13, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(14, 4, 15, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(15, 3)
    SetStartLocPrio(15, 0, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(15, 1, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(15, 2, 14, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(16, 15)
    SetStartLocPrio(16, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 8, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 9, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 10, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 11, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 12, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(16, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(17, 15)
    SetStartLocPrio(17, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 9, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 10, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 11, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 12, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(17, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(18, 15)
    SetStartLocPrio(18, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 10, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 11, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 12, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(18, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(19, 15)
    SetStartLocPrio(19, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 10, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 11, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 12, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(19, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(20, 15)
    SetStartLocPrio(20, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 10, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 11, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 12, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(20, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(21, 15)
    SetStartLocPrio(21, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 10, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 11, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 12, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 13, 22, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(21, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(22, 15)
    SetStartLocPrio(22, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 10, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 11, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 12, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 13, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(22, 14, 23, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(23, 15)
    SetStartLocPrio(23, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 3, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 5, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 6, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 7, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 8, 16, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 9, 17, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 10, 18, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 11, 19, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 12, 20, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 13, 21, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(23, 14, 22, MAP_LOC_PRIO_HIGH)
end

function main()
    SetCameraBounds(-29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -29952.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 29696.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 29952.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -30208.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronFallDay")
    SetAmbientNightSound("LordaeronFallNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_003")
    SetMapDescription("TRIGSTR_005")
    SetPlayers(24)
    SetTeams(24)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, -27456.0, 26816.0)
    DefineStartLocation(1, -27008.0, 26816.0)
    DefineStartLocation(2, -26560.0, 26816.0)
    DefineStartLocation(3, -26112.0, 26816.0)
    DefineStartLocation(4, -27456.0, 26368.0)
    DefineStartLocation(5, -27008.0, 26368.0)
    DefineStartLocation(6, -26560.0, 26368.0)
    DefineStartLocation(7, -26112.0, 26368.0)
    DefineStartLocation(8, 26048.0, -27456.0)
    DefineStartLocation(9, 26496.0, -27456.0)
    DefineStartLocation(10, 26944.0, -27456.0)
    DefineStartLocation(11, 27392.0, -27456.0)
    DefineStartLocation(12, 26048.0, -27904.0)
    DefineStartLocation(13, 26496.0, -27904.0)
    DefineStartLocation(14, 26944.0, -27904.0)
    DefineStartLocation(15, 27392.0, -27904.0)
    DefineStartLocation(16, 2944.0, 2112.0)
    DefineStartLocation(17, 2944.0, 1408.0)
    DefineStartLocation(18, -28480.0, 28096.0)
    DefineStartLocation(19, -27840.0, 28096.0)
    DefineStartLocation(20, -28480.0, 27456.0)
    DefineStartLocation(21, 28608.0, -29120.0)
    DefineStartLocation(22, 28608.0, -28544.0)
    DefineStartLocation(23, 28032.0, -29120.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

